
package com.unimet.interfaz;
import com.unimet.clases.GestorGraficas;
import com.unimet.clases.PCB;
import com.unimet.estructuras.Cola;



public class Simulacion extends javax.swing.JFrame {
    // --- INICIO DE PERSONALIZACIÓN VISUAL ---
    
    // Paleta de Colores "Cyberpunk / Espacial"
    java.awt.Color colorFondo = java.awt.Color.decode("#0F172A");    // Azul oscuro profundo
    java.awt.Color colorPanel = java.awt.Color.decode("#1E293B");    // Gris azulado
    java.awt.Color colorBorde = java.awt.Color.decode("#38BDF8");    // Cian Neón
    java.awt.Color colorTexto = java.awt.Color.decode("#E2E8F0");    // Blanco humo
    java.awt.Color colorVerde = java.awt.Color.decode("#22C55E");    // Verde Terminal
    java.awt.Color colorRojo  = java.awt.Color.decode("#EF4444");    // Rojo Alerta
    
    // Fuentes Personalizadas
    java.awt.Font fuenteTerminal = new java.awt.Font("Monospaced", java.awt.Font.BOLD, 12);
    java.awt.Font fuenteReloj    = new java.awt.Font("Impact", java.awt.Font.PLAIN, 24);
    java.awt.Font fuenteTitulo   = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Simulacion.class.getName());
// Tus colas
    Cola<PCB> colaListos = new Cola<>();
    Cola<PCB> colaBloqueados = new Cola<>();
    
    public static final int MAX_MEMORIA = 5; 
    
    // Colas para los procesos que NO caben en RAM (están en disco)
    Cola<PCB> colaListosSuspendidos = new Cola<>();
    Cola<PCB> colaBloqueadosSuspendidos = new Cola<>();
    GestorGraficas misGraficas; 
    
    PCB procesoEnCpu = null;
    boolean corriendo = false;
    int quantum = 5; // Cada proceso tiene solo 5 turnos seguidos
    int contadorQuantum = 0; // Para contar cuánto lleva el proceso actual
    int relojGlobal = 0;
    
    public Simulacion() {
        
        initComponents();
        aplicarTemaOscuro();
        spnQuantum.setValue(5);      // Quantum de 5 turnos
        spnVelocidad.setValue(1000); // 1 segundo de velocidad (para empezar lento)
        misGraficas = new GestorGraficas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtColaListos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtColaBloqueados = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        cmbAlgoritmos = new javax.swing.JComboBox<>();
        btnCrear20 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnQuantum = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spnVelocidad = new javax.swing.JSpinner();
        lblReloj = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBloqueadosSuspendidos = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtListosSuspendidos = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pbCpu = new javax.swing.JProgressBar();
        btnCargar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setText("COLA DE LISTOS");

        txtColaListos.setColumns(20);
        txtColaListos.setRows(5);
        jScrollPane1.setViewportView(txtColaListos);

        jLabel2.setText("COLA DE BLOQUEADOS");

        txtColaBloqueados.setColumns(20);
        txtColaBloqueados.setRows(5);
        jScrollPane2.setViewportView(txtColaBloqueados);

        jLabel3.setText("CPU - PROCESANDO");

        lblId.setText("ID: ---");

        lblEstado.setText("Estado: ---");

        btnIniciar.setText("Iniciar Simulación");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        btnCrear.setText("Crear Proceso");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        cmbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "RR", "Prioridad", "SRT", "EDF" }));
        cmbAlgoritmos.addActionListener(this::cmbAlgoritmosActionPerformed);

        btnCrear20.setText("Generar 20 Procesos Aleatorios");
        btnCrear20.addActionListener(this::btnCrear20ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnCrear20, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnCrear20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Quantum:");

        jLabel5.setText("Velocidad (ms):");

        lblReloj.setText("Reloj: 0");

        txtBloqueadosSuspendidos.setColumns(20);
        txtBloqueadosSuspendidos.setRows(5);
        jScrollPane3.setViewportView(txtBloqueadosSuspendidos);

        txtListosSuspendidos.setColumns(20);
        txtListosSuspendidos.setRows(5);
        jScrollPane4.setViewportView(txtListosSuspendidos);

        jLabel6.setText("Disco: Listos-Suspendidos");

        jLabel7.setText("Disco: Bloqueados-Suspendidos");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        jLabel8.setText("                                                               ");

        lblMemoria.setText("                                                                                                       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMemoria)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(186, 186, 186))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 81, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(spnQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMemoria))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        generarProcesosAleatorios(1); // Genera solo 1
        System.out.println("Proceso individual generado.");
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    // Evitar que le den click dos veces
    if (corriendo) return;
    corriendo = true;

    // HILO DEL PLANIFICADOR PRINCIPAL
    Thread hiloSimulacion = new Thread(() -> {
        while (corriendo) {
            try {
                // -----------------------------------------------------------
                // 1. LECTURA DE PARÁMETROS DE LA INTERFAZ
                // -----------------------------------------------------------
                int quantumActual = (Integer) spnQuantum.getValue();
                if (quantumActual < 1) quantumActual = 1;
                
                int velocidad = (Integer) spnVelocidad.getValue();
                if (velocidad < 0) velocidad = 0;

                // Avanzar el reloj del sistema
                relojGlobal++;
                // Usamos invokeLater para actualizar la GUI desde otro hilo (Recomendado)
                javax.swing.SwingUtilities.invokeLater(() -> lblReloj.setText("Reloj Global: " + relojGlobal));

                // -----------------------------------------------------------
                // 2. GESTIÓN DE BLOQUEADOS (E/S) - RAM Y DISCO
                // -----------------------------------------------------------
                
                // A. Bloqueados en RAM
                int sizeBloq = colaBloqueados.getSize();
                for(int i=0; i<sizeBloq; i++) {
                    PCB bloqueado = colaBloqueados.desencolar();
                    if(bloqueado != null) {
                        bloqueado.setLongitudBloqueo(bloqueado.getLongitudBloqueo() - 1);

                        if (bloqueado.getLongitudBloqueo() <= 0) {
                            // Terminó E/S -> Va a Listo (RAM o Disco según espacio)
                            System.out.println(">>> Fin I/O (RAM): " + bloqueado.getNombre());
                            bloqueado.setEstado("Listo");
                            bloqueado.setCicloParaBloqueo(-1);
                            agregarAColaListos(bloqueado); 
                        } else {
                            colaBloqueados.encolar(bloqueado);
                        }
                    }
                }

                // B. Bloqueados en DISCO (Suspendidos)
                int sizeBloqSusp = colaBloqueadosSuspendidos.getSize();
                for(int i=0; i<sizeBloqSusp; i++) {
                    PCB bSusp = colaBloqueadosSuspendidos.desencolar();
                    if(bSusp != null) {
                        bSusp.setLongitudBloqueo(bSusp.getLongitudBloqueo() - 1);

                        if (bSusp.getLongitudBloqueo() <= 0) {
                            // Terminó E/S en Disco -> Pasa a Listos-Suspendidos
                            System.out.println(">>> Fin I/O (Disco): " + bSusp.getNombre());
                            bSusp.setEstado("Listo-Suspendido");
                            bSusp.setCicloParaBloqueo(-1);
                            colaListosSuspendidos.encolar(bSusp);
                        } else {
                            colaBloqueadosSuspendidos.encolar(bSusp);
                        }
                    }
                }

                // Intentar subir procesos de Disco a RAM si se liberó espacio arriba
                revisarSuspendidos(); 

                // -----------------------------------------------------------
                // 3. PLANIFICADOR DE CPU (DISPATCHER)
                // -----------------------------------------------------------
                if (procesoEnCpu == null) {
                    if (!colaListos.isEmpty()) {
                        procesoEnCpu = colaListos.desencolar();
                        procesoEnCpu.setEstado("Ejecucion");
                        contadorQuantum = 0;
                        
                        // Actualizar GUI
                        PCB pRef = procesoEnCpu; 
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            lblId.setText("ID: " + pRef.getId());
                            lblEstado.setText("Ejecutando (" + cmbAlgoritmos.getSelectedItem() + ")");
                        });
                    } else {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            lblId.setText("ID: --- (IDLE)");
                            lblEstado.setText("Esperando procesos...");
                            pbCpu.setValue(0);
                        });
                    }
                }

                // -----------------------------------------------------------
                // 4. EJECUCIÓN DEL PROCESO
                // -----------------------------------------------------------
                if (procesoEnCpu != null) {
                    
                    // A. VERIFICAR DEADLINE (REQUERIMIENTO CRÍTICO)
                    if (relojGlobal > procesoEnCpu.getDeadline()) {
                        System.out.println(">>> FALLO DE DEADLINE: Proceso " + procesoEnCpu.getId());
                        misGraficas.registrarFallo();
                        procesoEnCpu.setEstado("Terminado (Fallo)");
                        procesoEnCpu = null;
                        
                        javax.swing.SwingUtilities.invokeLater(() -> lblId.setText("ID: --- (Fallo Deadline)"));
                        // Aquí podrías incrementar un contador de fallos
                    }
                    else {
                        // B. VERIFICAR SI TOCA BLOQUEO POR E/S
                        if (procesoEnCpu.getInstruccionesEjecutadas() == procesoEnCpu.getCicloParaBloqueo()) {
                            System.out.println(">>> Bloqueo por E/S: Proceso " + procesoEnCpu.getId());
                            procesoEnCpu.setEstado("Bloqueado");
                            
                            // Verificar si cabe en RAM o va a Disco
                            if (getOcupacionMemoria() <= MAX_MEMORIA) {
                                colaBloqueados.encolar(procesoEnCpu);
                            } else {
                                // Si la RAM está explotada, el bloqueado se va a disco
                                procesoEnCpu.setEstado("Bloqueado-Suspendido");
                                colaBloqueadosSuspendidos.encolar(procesoEnCpu);
                            }
                            
                            procesoEnCpu = null;
                            javax.swing.SwingUtilities.invokeLater(() -> lblId.setText("ID: --- (Bloqueado)"));
                        }
                        // C. EJECUTAR INSTRUCCIÓN
                        else {
                            procesoEnCpu.avanzarInstruccion();
                            contadorQuantum++;

                            // Actualizar Barra de Progreso
                            int total = procesoEnCpu.getInstruccionesTotales();
                            int actual = procesoEnCpu.getInstruccionesEjecutadas();
                            int porcentaje = (actual * 100) / total;
                            
                            javax.swing.SwingUtilities.invokeLater(() -> {
                                pbCpu.setValue(porcentaje);
                                pbCpu.setString(actual + " / " + total + " Instr");
                                if(porcentaje > 80) pbCpu.setForeground(java.awt.Color.ORANGE);
                                else pbCpu.setForeground(java.awt.Color.decode("#22C55E"));
                            });

                            // D. VERIFICAR FIN DE PROCESO
                            if (actual >= total) {
                                System.out.println(">>> Terminado: " + procesoEnCpu.getId());
                                misGraficas.registrarExito();
                                procesoEnCpu.setEstado("Terminado");
                                procesoEnCpu = null;
                                javax.swing.SwingUtilities.invokeLater(() -> lblId.setText("ID: --- (Terminado)"));
                                revisarSuspendidos(); // Ver si alguien sube
                            }
                            // E. VERIFICAR FIN DE QUANTUM (Solo RR)
                            else if (cmbAlgoritmos.getSelectedItem().equals("RR") && contadorQuantum >= quantumActual) {
                                System.out.println(">>> Fin Quantum: " + procesoEnCpu.getId());
                                procesoEnCpu.setEstado("Listo");
                                agregarAColaListos(procesoEnCpu);
                                procesoEnCpu = null;
                                contadorQuantum = 0;
                                javax.swing.SwingUtilities.invokeLater(() -> lblId.setText("ID: --- (Timeout)"));
                            }
                        }
                    }
                }

                // -----------------------------------------------------------
                // 5. ACTUALIZACIÓN FINAL DE COLAS VISUALES
                // -----------------------------------------------------------
                javax.swing.SwingUtilities.invokeLater(() -> refrescarColaListos());
                int ocupados = getOcupacionMemoria();
                    lblMemoria.setText("Memoria RAM: " + ocupados + "/" + MAX_MEMORIA);
                    
                    // Truco visual: Si está llena (5/5), ponlo en ROJO, si no, en VERDE
                    if (ocupados >= MAX_MEMORIA) {
                        lblMemoria.setForeground(java.awt.Color.RED);
                        lblMemoria.setText("Memoria RAM: ¡LLENA! (" + ocupados + "/" + MAX_MEMORIA + ")");
                    } else {
                        lblMemoria.setForeground(java.awt.Color.GREEN);
                    }
                
                Thread.sleep(velocidad);

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    });
    hiloSimulacion.start();
    Thread hiloInterrupciones = new Thread(() -> {
        while (corriendo) {
            try {
                // 1. Esperar un tiempo aleatorio largo (ej. entre 10 y 20 segundos)
                // Para que no sea molesto, que pase poco.
                int tiempoEspera = (int)(Math.random() * 10000) + 10000; 
                Thread.sleep(tiempoEspera);

                // 2. Crear una Interrupción (Proceso de Prioridad 0 - MÁXIMA)
                PCB interrupcion = new PCB("ALERTA: FALLO MOTOR", 0, 20, 100);
                interrupcion.setEstado("Listo");

                // 3. Meterlo a la fuerza en la cola de Listos (al principio si es prioridad)
                colaListos.insertarOrdenado(interrupcion, Cola.CRITERIO_PRIORIDAD);

                System.out.println("!!! INTERRUPCIÓN GENERADA: " + interrupcion.getNombre());

                // 4. (Opcional) Si quieres ser muy estricto, podrías sacar al CPU aquí mismo
                // Pero el planificador lo hará solo en la siguiente vuelta.

            } catch (InterruptedException e) { e.printStackTrace(); }
        }
    });
    hiloInterrupciones.start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void cmbAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlgoritmosActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int seleccion = fileChooser.showOpenDialog(this);
    
    if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                // Asumimos formato CSV: Nombre,Prioridad,Instrucciones,Deadline
                // Ejemplo: ProcesoA,1,50,200
                String[] datos = linea.split(",");
                if (datos.length == 4) {
                    String nombre = datos[0].trim();
                    int prio = Integer.parseInt(datos[1].trim());
                    int inst = Integer.parseInt(datos[2].trim());
                    int dead = Integer.parseInt(datos[3].trim());
                    
                    PCB nuevo = new PCB(nombre, prio, inst, dead);
                    agregarAColaListos(nuevo); // Reutilizamos tu lógica de agregar
                }
            }
            System.out.println("Archivo cargado exitosamente.");
            refrescarColaListos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnCrear20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear20ActionPerformed
        generarProcesosAleatorios(20); // Genera los 20 de golpe
        System.out.println("Generación masiva de 20 procesos ejecutada.");
    }//GEN-LAST:event_btnCrear20ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Simulacion().setVisible(true));
    }
    
    // Este método actualiza el cuadro de texto con los procesos que quedan
    private void refrescarColaListos() {
        // 1. Limpiar y llenar Listos (RAM)
        txtColaListos.setText(""); 
        if (!colaListos.isEmpty()) txtColaListos.setText(colaListos.toString());
        
        // 2. Limpiar y llenar Bloqueados (RAM)
        txtColaBloqueados.setText("");
        if (!colaBloqueados.isEmpty()) txtColaBloqueados.setText(colaBloqueados.toString());
        
        // 3. Limpiar y llenar Suspendidos (Disco) <-- ESTO ES LO NUEVO
        txtListosSuspendidos.setText("");
        if (!colaListosSuspendidos.isEmpty()) txtListosSuspendidos.setText(colaListosSuspendidos.toString());
        
        txtBloqueadosSuspendidos.setText("");
        if (!colaBloqueadosSuspendidos.isEmpty()) txtBloqueadosSuspendidos.setText(colaBloqueadosSuspendidos.toString());
    }
    
    public void agregarAColaListos(PCB proceso) {
        String algoritmo = (String) cmbAlgoritmos.getSelectedItem();

        // 1. Insertar en la cola según algoritmo
        switch (algoritmo) {
            case "FCFS":
            case "RR":
                colaListos.encolar(proceso); 
                break;
            case "Prioridad":
                colaListos.insertarOrdenado(proceso, 0); // 0 = Criterio Prioridad
                break;
            case "SRT":
                colaListos.insertarOrdenado(proceso, 1); // 1 = Criterio Tiempo Restante
                break;
            case "EDF":
                colaListos.insertarOrdenado(proceso, 2); // 2 = Criterio Deadline
                break;
        }

    // 2. LOGICA DE EXPROPIACIÓN (PREEMPTION) - PARA EL 20 PUNTOS
    // Si hay alguien en CPU y el algoritmo lo permite, verificamos si el nuevo es mejor
        if (procesoEnCpu != null) {
            boolean debeExpropiar = false;

            // Solo expropiamos en algoritmos apropiativos
            if (algoritmo.equals("Prioridad") && proceso.getPrioridad() < procesoEnCpu.getPrioridad()) {
                debeExpropiar = true;
            } else if (algoritmo.equals("SRT") && 
                       (proceso.getInstruccionesTotales() - proceso.getInstruccionesEjecutadas()) < 
                       (procesoEnCpu.getInstruccionesTotales() - procesoEnCpu.getInstruccionesEjecutadas())) {
                debeExpropiar = true;
            } else if (algoritmo.equals("EDF") && proceso.getDeadline() < procesoEnCpu.getDeadline()) {
                debeExpropiar = true;
            }

            if (debeExpropiar) {
                System.out.println("!!! EXPROPIACIÓN: " + proceso.getNombre() + " saca a " + procesoEnCpu.getNombre());

                // Sacamos al actual del CPU
                PCB saliente = procesoEnCpu;
                saliente.setEstado("Listo");

                // Lo devolvemos a la cola (llamada recursiva segura porque procesoEnCpu ya no será null al entrar)
                // Ojo: Para evitar bucle infinito, lo metemos directo a la cola segun su tipo
                switch (algoritmo) {
                    case "Prioridad": colaListos.insertarOrdenado(saliente, 0); break;
                    case "SRT":       colaListos.insertarOrdenado(saliente, 1); break;
                    case "EDF":       colaListos.insertarOrdenado(saliente, 2); break;
                }

                procesoEnCpu = null; // Liberamos CPU para que el Hilo tome al nuevo (que quedó de primero)
                contadorQuantum = 0;
                lblId.setText("ID: --- (Expropiado)");
            }
        }

        refrescarColaListos();
    }    
    // Cuenta cuántos procesos ocupan espacio en RAM actualmente
    private int getOcupacionMemoria() {
        int ocupados = colaListos.getSize() + colaBloqueados.getSize();
        if (procesoEnCpu != null) {
            ocupados++;
        }
        return ocupados;
    }
    
    // ESTE MÉTODO MUEVE PROCESOS DEL DISCO A LA RAM
    private void revisarSuspendidos() {
        // Mientras haya espacio en RAM (menos de 5 procesos) Y haya gente esperando en disco
        while (getOcupacionMemoria() < MAX_MEMORIA && !colaListosSuspendidos.isEmpty()) {

            // 1. Sacamos al primero de la lista de SUSPENDIDOS (Disco)
            PCB rescatado = colaListosSuspendidos.desencolar();

            if (rescatado != null) {
                // 2. Lo pasamos a RAM
                rescatado.setEstado("Listo");

                // 3. Lo insertamos en la cola de listos de RAM según el algoritmo actual
                // IMPORTANTE: Usamos insertarOrdenado para respetar prioridades o SRT
                String algoritmo = (String) cmbAlgoritmos.getSelectedItem();

                switch (algoritmo) {
                    case "Prioridad": 
                        // 0 = Criterio Prioridad (Menor número gana)
                        colaListos.insertarOrdenado(rescatado, Cola.CRITERIO_PRIORIDAD); 
                        break;
                    case "SRT":       
                        // 1 = Criterio Tiempo Restante (Menor tiempo gana)
                        colaListos.insertarOrdenado(rescatado, Cola.CRITERIO_SRT); 
                        break;
                    case "EDF":       
                        // 2 = Criterio Deadline (Plazo más cercano gana)
                        colaListos.insertarOrdenado(rescatado, Cola.CRITERIO_EDF); 
                        break;
                    default:          
                        // FCFS o RR (Al final de la cola)
                        colaListos.encolar(rescatado); 
                        break;
                }

                System.out.println(">>> SWAP IN: Proceso " + rescatado.getId() + " subió del Disco a la RAM.");
            }
        }
    }
    
    // MÉTODO MÁGICO PARA ESTILIZAR LA INTERFAZ
    private void aplicarTemaOscuro() {
        // 1. Fondo Principal
        this.getContentPane().setBackground(colorFondo);
        this.setTitle("UNIMET-Sat RTOS | Mission Control Center");
        
        // 2. Estilizar Colas (JTextAreas)
        estilizarCola(txtColaListos, "RAM: Cola de Listos");
        estilizarCola(txtColaBloqueados, "RAM: Bloqueados (I/O)");
        estilizarCola(txtListosSuspendidos, "DISCO: Swap Listos");
        estilizarCola(txtBloqueadosSuspendidos, "DISCO: Swap Bloqueados");
        
        // 3. Estilizar Panel CPU (Centro)
        jPanel1.setBackground(colorPanel);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(colorBorde, 2),
            javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        
        // 4. Estilizar Etiquetas (Labels)
        // Reloj Global estilo Digital
        lblReloj.setFont(fuenteReloj);
        lblReloj.setForeground(colorBorde);
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setBorder(javax.swing.BorderFactory.createLineBorder(colorBorde));
        
        // Etiquetas generales
        javax.swing.JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, lblId, lblEstado};
        for (javax.swing.JLabel lbl : labels) {
            lbl.setForeground(colorTexto);
            if (lbl == lblId || lbl == lblEstado) {
                lbl.setFont(fuenteTerminal.deriveFont(14f));
                lbl.setForeground(colorVerde);
            }
        }

        // 5. Botones Estilo Plano
        estilizarBoton(btnIniciar, colorVerde);
        estilizarBoton(btnCrear, colorBorde);
        
        // 6. Controles (Spinner y Combo)
        cmbAlgoritmos.setBackground(colorPanel);
        cmbAlgoritmos.setForeground(java.awt.Color.WHITE); // Ojo: A veces Swing resiste cambios en ComboBox
    }

    // Auxiliar para JTextAreas
    private void estilizarCola(javax.swing.JTextArea txt, String titulo) {
        txt.setBackground(java.awt.Color.BLACK);
        txt.setForeground(colorVerde);
        txt.setFont(fuenteTerminal);
        txt.setCaretColor(java.awt.Color.WHITE);
        
        // Borde con Título incorporado
        javax.swing.border.TitledBorder bordeTitulo = javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY),
            titulo
        );
        bordeTitulo.setTitleColor(colorTexto);
        bordeTitulo.setTitleFont(fuenteTitulo);
        
        // Aplicamos el borde al ScrollPane que contiene el TextArea (es el padre)
        if (txt.getParent() != null && txt.getParent().getParent() instanceof javax.swing.JScrollPane) {
            ((javax.swing.JScrollPane)txt.getParent().getParent()).setBorder(bordeTitulo);
            ((javax.swing.JScrollPane)txt.getParent().getParent()).setBackground(colorPanel);
        }
    }

    // Auxiliar para Botones
    private void estilizarBoton(javax.swing.JButton btn, java.awt.Color color) {
        btn.setBackground(color);
        btn.setForeground(java.awt.Color.BLACK); // Texto oscuro para contraste
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btn.setFocusPainted(false);
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    // Método centralizado para generar N procesos aleatorios
    private void generarProcesosAleatorios(int cantidad) {
        for (int i = 0; i < cantidad; i++) {
            int instrucciones = (int) (Math.random() * 100) + 10;
            int prioridad = (int) (Math.random() * 3) + 1; // Prioridad 1, 2 o 3
            int deadline = relojGlobal + (int) (Math.random() * 200) + 50; 
            
            String nombre = "Proceso-" + (int)(Math.random() * 1000);
            PCB nuevoProceso = new PCB(nombre, prioridad, instrucciones, deadline);
            
            if (getOcupacionMemoria() < MAX_MEMORIA) {
                nuevoProceso.setEstado("Listo");
                agregarAColaListos(nuevoProceso);
            } else {
                nuevoProceso.setEstado("Listo-Suspendido");
                colaListosSuspendidos.encolar(nuevoProceso);
                System.out.println("Memoria llena. " + nombre + " a Suspendidos.");
            }
        }
        revisarSuspendidos();
        refrescarColaListos();
    }
    
    // --- FIN DE LO QUE TIENES QUE PEGAR ---
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrear20;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> cmbAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JProgressBar pbCpu;
    private javax.swing.JSpinner spnQuantum;
    private javax.swing.JSpinner spnVelocidad;
    private javax.swing.JTextArea txtBloqueadosSuspendidos;
    private javax.swing.JTextArea txtColaBloqueados;
    private javax.swing.JTextArea txtColaListos;
    private javax.swing.JTextArea txtListosSuspendidos;
    // End of variables declaration//GEN-END:variables
}
